/* LIMPA AS INFORMAÇÕES DO BANCO CASO EXISTAM*/
/*
DROP TABLE PEDIDO_PRODUTO;
DROP TABLE CLIENTE;
DROP TABLE PRODUTO;
DROP TABLE PEDIDO;
DROP TABLE USUARIO;

DROP SEQUENCE SEQ_ID_CLIENTE;
DROP SEQUENCE SEQ_ID_PRODUTO;
DROP SEQUENCE SEQ_ID_PEDIDO;

DROP TRIGGER TR_ID_CLIENTE;
DROP TRIGGER TR_ID_PRODUTO;
DROP TRIGGER TR_ID_PEDIDO;
*/

CREATE TABLE CLIENTE(	ID_CLIENTE NUMBER NOT NULL, 
			NOME VARCHAR2(200), 
			NOME_FANTASIA VARCHAR2(200), 
			CPF VARCHAR2(11),
			CNPJ VARCHAR2(14), 
			TELEFONE VARCHAR2(11), 
			EMAIL VARCHAR2(30), 
			RUA VARCHAR2(60), 
			NUMERO NUMBER(5), 
			BAIRRO VARCHAR2(40), 
			CIDADE VARCHAR2(40), 
			CEP VARCHAR2(8),
			COMPLEMENTO VARCHAR2(40));

CREATE TABLE PRODUTO(ID_PRODUTO NUMBER NOT NULL, 
		     DESCRICAO VARCHAR2(40), 
		     PRECO NUMBER, 
		     QTD_ITENS NUMBER);


CREATE TABLE PEDIDO(	ID_PEDIDO NUMBER NOT NULL, 
			ID_CLIENTE NUMBER NOT NULL, 
			RUA VARCHAR2(40), 
			NUMERO NUMBER, 
			BAIRRO VARCHAR2(40), 
			CIDADE VARCHAR2(40), 
			CEP VARCHAR2(40), 
			COMPLEMENTO VARCHAR2(40), 
			VALOR_TOTAL NUMBER, 
			DATA_PEDIDO DATE, 
			DATA_ENTREGA DATE, 
			FORMA_PAGAMENTO VARCHAR2(1), 
			OBS VARCHAR2(40),
			SN_RETIRAR_LOJA VARCHAR2(1),  
			STATUS VARCHAR2(1));

CREATE TABLE PEDIDO_PRODUTO(	ID_PEDIDO_PRODUTO NUMBER NOT NULL,
                ID_PEDIDO NUMBER NOT NULL, 
				ID_PRODUTO NUMBER NOT NULL, 
				QTD NUMBER NOT NULL, 
				VALOR_UNITARIO NUMBER NOT NULL);

CREATE TABLE USUARIO(	CPF VARCHAR2(11) NOT NULL,
			NOME VARCHAR2(20), 
			SENHA VARCHAR2(30));

/* CHAVE PRIMARIA*/
ALTER TABLE CLIENTE ADD CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE);
ALTER TABLE PRODUTO ADD CONSTRAINT PK_ID_PRODUTO PRIMARY KEY (ID_PRODUTO);
ALTER TABLE PEDIDO  ADD CONSTRAINT PK_ID_PEDIDO PRIMARY KEY (ID_PEDIDO);
ALTER TABLE USUARIO ADD CONSTRAINT PK_CPF PRIMARY KEY (CPF);

/* CHAVE ESTRANGEIRA*/
ALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_ID_CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);
ALTER TABLE PEDIDO_PRODUTO ADD CONSTRAINT PEDIDO_PRODUTO_ID_PRODUTO_FK FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO);
ALTER TABLE PEDIDO_PRODUTO ADD CONSTRAINT PEDIDO_PRODUTO_ID_PEDIDO_FK FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO);

/* RESTRIÇÃO */

--ALTER TABLE PEDIDO ADD CONSTRAINT CK_FORMA_PAGAMENTO CHECK(FORMA_PAGAMENTO IN ('D','C'));/* D- DINHEIRO, C- CARTÃO*/
--ALTER TABLE PEDIDO ADD CONSTRAINT CK_SN_RETIRAR_LOJA CHECK(SN_RETIRAR_LOJA IN ('S','N'));/* S- SIM, N- NÃO*/
--ALTER TABLE PEDIDO ADD CONSTRAINT CK_STATUS CHECK(STATUS IN ('F','C'));/* F- FATURADO, C- CANCELADO*/

/* SEQUENCIA */
CREATE SEQUENCE SEQ_ID_CLIENTE  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ID_PRODUTO  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ID_PEDIDO  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ID_PEDIDO_PRODUTO  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;

/*TRIGGER*/
/*
CREATE OR REPLACE TRIGGER TR_ID_CLIENTE
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
 SELECT SEQ_ID_CLIENTE.NEXTVAL INTO :NEW.ID_CLIENTE
 FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TR_ID_PRODUTO
BEFORE INSERT ON PRODUTO
FOR EACH ROW
BEGIN
 SELECT SEQ_ID_PRODUTO.NEXTVAL INTO :NEW.ID_PRODUTO
 FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TR_ID_PEDIDO
BEFORE INSERT ON PEDIDO
FOR EACH ROW
BEGIN
 SELECT SEQ_ID_PEDIDO.NEXTVAL INTO :NEW.ID_PEDIDO
 FROM DUAL;
END;

INSERT INTO USUARIO(CPF, NOME, SENHA) VALUES ('11111111111','ADMIN','ADMIN' );


INSERT INTO PRODUTO(DESCRICAO, PRECO, QTD_ITENS) VALUES('TESTE',1.5,2);

COMMIT;
*/



